DEMO_ADDRESSES = [
    {
        "address_line_1": "10 Downing Street",
        "address_line_2": "",
        "town_city": "London",
        "county": "Greater London",
        "postcode": "SW1A 2AA",
    },
    {
        "address_line_1": "The Old Rectory",
        "address_line_2": "High Street",
        "town_city": "Reading",
        "county": "Berkshire",
        "postcode": "RG1 1AA",
    },
    {
        "address_line_1": "Flat 4, Miller House",
        "address_line_2": "12 Industrial Way",
        "town_city": "Manchester",
        "county": "Greater Manchester",
        "postcode": "M1 4BT",
    },
    {
        "address_line_1": "15 Gladstone Road",
        "address_line_2": "",
        "town_city": "Brighton",
        "county": "East Sussex",
        "postcode": "BN1 6RL",
    },
    {
        "address_line_1": "Flat 12",
        "address_line_2": "Harbour View",
        "town_city": "Southampton",
        "county": "Hampshire",
        "postcode": "SO14 3ZH",
    },
    {
        "address_line_1": "Oak Tree Cottage",
        "address_line_2": "School Lane",
        "town_city": "Burford",
        "county": "Oxfordshire",
        "postcode": "OX18 4JL",
    },
    {
        "address_line_1": "Unit 3",
        "address_line_2": "Innovation Way",
        "town_city": "Cambridge",
        "county": "Cambridgeshire",
        "postcode": "CB4 0WZ",
    },
    {
        "address_line_1": "74 Princes Street",
        "address_line_2": "",
        "town_city": "Edinburgh",
        "county": "Midlothian",
        "postcode": "EH2 2ER",
    },
    {
        "address_line_1": "29 Windsor Terrace",
        "address_line_2": "",
        "town_city": "Newcastle upon Tyne",
        "county": "Tyne and Wear",
        "postcode": "NE2 4HE",
    },
    {
        "address_line_1": "The Granary",
        "address_line_2": "Mill Road",
        "town_city": "Norwich",
        "county": "Norfolk",
        "postcode": "NR1 1AL",
    },
    {
        "address_line_1": "102 Corporation Street",
        "address_line_2": "",
        "town_city": "Birmingham",
        "county": "West Midlands",
        "postcode": "B4 6QB",
    },
    {
        "address_line_1": "Apartment 5",
        "address_line_2": "St Peters Square",
        "town_city": "Manchester",
        "county": "Greater Manchester",
        "postcode": "M2 3AE",
    },
    {
        "address_line_1": "88 Queen Street",
        "address_line_2": "",
        "town_city": "Cardiff",
        "county": "South Glamorgan",
        "postcode": "CF10 2FG",
    },
    {
        "address_line_1": "19 Highfield Avenue",
        "address_line_2": "",
        "town_city": "York",
        "county": "North Yorkshire",
        "postcode": "YO10 3LQ",
    },
    {
        "address_line_1": "Suite 210",
        "address_line_2": "Regent House",
        "town_city": "Leeds",
        "county": "West Yorkshire",
        "postcode": "LS2 7QN",
    },
    {
        "address_line_1": "56 Lowther Street",
        "address_line_2": "",
        "town_city": "Carlisle",
        "county": "Cumbria",
        "postcode": "CA3 8DP",
    },
    {
        "address_line_1": "Rowan House",
        "address_line_2": "Church Lane",
        "town_city": "Lincoln",
        "county": "Lincolnshire",
        "postcode": "LN2 1QH",
    },
    {
        "address_line_1": "12 Victoria Street",
        "address_line_2": "",
        "town_city": "Liverpool",
        "county": "Merseyside",
        "postcode": "L2 6QE",
    },
    {
        "address_line_1": "Apartment 42",
        "address_line_2": "Skyline Plaza",
        "town_city": "Reading",
        "county": "Berkshire",
        "postcode": "RG1 1AY",
    },
    {
        "address_line_1": "44 George Street",
        "address_line_2": "",
        "town_city": "Perth",
        "county": "Perthshire",
        "postcode": "PH1 5JL",
    },
    {
        "address_line_1": "The Old Smithy",
        "address_line_2": "Main Street",
        "town_city": "Bakewell",
        "county": "Derbyshire",
        "postcode": "DE45 1DZ",
    },
    {
        "address_line_1": "21 Market Place",
        "address_line_2": "",
        "town_city": "Warwick",
        "county": "Warwickshire",
        "postcode": "CV34 4SA",
    },
    {
        "address_line_1": "Upper Flat",
        "address_line_2": "33 North Road",
        "town_city": "Durham",
        "county": "County Durham",
        "postcode": "DH1 4SE",
    },
    {
        "address_line_1": "90 Victoria Embankment",
        "address_line_2": "",
        "town_city": "London",
        "county": "Greater London",
        "postcode": "EC4Y 0DH",
    },
    {
        "address_line_1": "67 Ship Street",
        "address_line_2": "",
        "town_city": "Oxford",
        "county": "Oxfordshire",
        "postcode": "OX1 3DA",
    },
    {
        "address_line_1": "Flat B",
        "address_line_2": "15 Montpellier Terrace",
        "town_city": "Cheltenham",
        "county": "Gloucestershire",
        "postcode": "GL50 1UX",
    },
    {
        "address_line_1": "The Coach House",
        "address_line_2": "Park Lane",
        "town_city": "Bath",
        "county": "Somerset",
        "postcode": "BA1 2XQ",
    },
    {
        "address_line_1": "14 Castle Street",
        "address_line_2": "",
        "town_city": "Inverness",
        "county": "Inverness-shire",
        "postcode": "IV2 3EE",
    },
    {
        "address_line_1": "89 Guildhall Street",
        "address_line_2": "",
        "town_city": "Bury St Edmunds",
        "county": "Suffolk",
        "postcode": "IP33 1PR",
    },
    {
        "address_line_1": "Unit 12",
        "address_line_2": "Industrial Estate",
        "town_city": "Swansea",
        "county": "West Glamorgan",
        "postcode": "SA1 8PH",
    },
    {
        "address_line_1": "25 Cathedral Yard",
        "address_line_2": "",
        "town_city": "Exeter",
        "county": "Devon",
        "postcode": "EX1 1HB",
    },
    {
        "address_line_1": "7 High Street",
        "address_line_2": "",
        "town_city": "St Andrews",
        "county": "Fife",
        "postcode": "KY16 9EE",
    },
    {
        "address_line_1": "45 Grey Street",
        "address_line_2": "",
        "town_city": "Newcastle upon Tyne",
        "county": "Tyne and Wear",
        "postcode": "NE1 6EE",
    },
    {
        "address_line_1": "Mansion House",
        "address_line_2": "The Walk",
        "town_city": "Doncaster",
        "county": "South Yorkshire",
        "postcode": "DN1 3EE",
    },
    {
        "address_line_1": "101 London Road",
        "address_line_2": "",
        "town_city": "Leicester",
        "county": "Leicestershire",
        "postcode": "LE2 0PF",
    },
    {
        "address_line_1": "Flat 3, 12 Belgrave Crescent",
        "address_line_2": "",
        "town_city": "Scarborough",
        "county": "North Yorkshire",
        "postcode": "YO11 1UB",
    },
    {
        "address_line_1": "8 Brompton Road",
        "address_line_2": "",
        "town_city": "London",
        "county": "Greater London",
        "postcode": "SW1X 7QN",
    },
    {
        "address_line_1": "The Gables",
        "address_line_2": "Station Road",
        "town_city": "Windermere",
        "county": "Cumbria",
        "postcode": "LA23 1AD",
    },
    {
        "address_line_1": "59 King Street",
        "address_line_2": "",
        "town_city": "Knutsford",
        "county": "Cheshire",
        "postcode": "WA16 6DX",
    },
    {
        "address_line_1": "Room 2.4",
        "address_line_2": "The Hive",
        "town_city": "Worcester",
        "county": "Worcestershire",
        "postcode": "WR1 3PD",
    },
    {
        "address_line_1": "18 Royal Terrace",
        "address_line_2": "",
        "town_city": "Glasgow",
        "county": "Lanarkshire",
        "postcode": "G3 7NY",
    },
    {
        "address_line_1": "62 Fore Street",
        "address_line_2": "",
        "town_city": "St Ives",
        "county": "Cornwall",
        "postcode": "TR26 1HE",
    },
    {
        "address_line_1": "72 Watergate Street",
        "address_line_2": "",
        "town_city": "Chester",
        "county": "Cheshire",
        "postcode": "CH1 2LA",
    },
    {
        "address_line_1": "Unit 9",
        "address_line_2": "Business Centre",
        "town_city": "Belfast",
        "county": "County Antrim",
        "postcode": "BT1 2LD",
    },
    {
        "address_line_1": "14 Turl Street",
        "address_line_2": "",
        "town_city": "Oxford",
        "county": "Oxfordshire",
        "postcode": "OX1 3DQ",
    },
    {
        "address_line_1": "Bridge Cottage",
        "address_line_2": "River Side",
        "town_city": "Salisbury",
        "county": "Wiltshire",
        "postcode": "SP1 2NF",
    },
    {
        "address_line_1": "31 Broad Street",
        "address_line_2": "",
        "town_city": "Aberdeen",
        "county": "Aberdeenshire",
        "postcode": "AB10 1QS",
    },
    {
        "address_line_1": "The Anchorage",
        "address_line_2": "Harbour Way",
        "town_city": "Whitby",
        "county": "North Yorkshire",
        "postcode": "YO21 3RR",
    },
    {
        "address_line_1": "99 Jubilee Crescent",
        "address_line_2": "",
        "town_city": "Coventry",
        "county": "West Midlands",
        "postcode": "CV6 3EX",
    },
    {
        "address_line_1": "Flat 1A, 22 Park Row",
        "address_line_2": "",
        "town_city": "Nottingham",
        "county": "Nottinghamshire",
        "postcode": "NG1 6GR",
    }
]